In [ ]:
!pip install pandas numpy openai sentence-transformers datasets transformers[torch] accelerate>=1.1.0 seaborn hdbscan umap-learn nltk plotly optuna BERTopic "git+https://github.com/FelSiq/DBCV"

In [2]:
%load_ext cuml.accel

/usr/local/lib/python3.12/dist-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

cuML: Installed accelerator for sklearn.
cuML: Installed accelerator for umap.
cuML: Installed accelerator for hdbscan.
cuML: Successfully initialized accelerator.

In [2]:
import pandas as pd
import numpy as np
import os
import json
from tqdm import tqdm
from pydantic import BaseModel, Field
from typing import Literal
from openai import OpenAI
import random
import torch
from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import safetensors
import umap
import hdbscan
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics.pairwise import cosine_similarity
import plotly.express as px
import plotly.graph_objects as go
import textwrap
import gc
import re
import requests
import html
import re
import torch
import numpy as np
import pandas as pd
from tqdm import tqdm
from transformers import AutoTokenizer, AutoModelForSequenceClassification

/usr/local/lib/python3.12/dist-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
pd.set_option('display.max_columns', None)

# Data Preprocessing

1. Load the full data extracted from Neo4j
2. Select only bill types that are Motion or Parliamentary Initiative
3. Format the bill number compliant with the Affair_ID to later fetch bill metadata 
4. Select the top 25 multilingual bills by # of paragraphs
5. Use NLI to classify whether a paragraph is procedural or not, and filter out procedural paragraphs
6. Aggregate the (non-procedural) paragraphs at the speech level

In [4]:
def normalize_swiss_bill(val):
    # Handle missing/NaN values safely
    if pd.isna(val) or val == 'nan':
        return np.nan

    # Ensure it is processed as a string representation of the float
    val_str = str(val).strip()
    if '.' not in val_str:
        return val_str

    left, right = val_str.split('.')

    # 1. Left-pad the year to 2 digits
    normalized_left = left.zfill(2)

    # 2. Right-pad the sequence to at least 3 digits
    normalized_right = right.ljust(3, '0')

    return f"{normalized_left}.{normalized_right}"

In [5]:
def fetch_bill_metadata(affair_id: str):
    if pd.isna(affair_id):
        return None

    url = f"https://ws-old.parlament.ch/affairs/{affair_id}?lang=en&format=json"
    headers = {"Accept": "application/json"}

    response = requests.get(url, headers=headers)

    if response.ok:
        data = response.json()

        # --- NEW: Extracting from the exact JSON schema provided ---
        extracted_keywords = []

        # Loop through the descriptors array to extract names
        descriptors = data.get('descriptors', [])
        if isinstance(descriptors, list):
            for item in descriptors:
                name = item.get('name')
                if name:
                    extracted_keywords.append(name.strip())

        # Fallback to additionalIndexing if descriptors are missing
        if not extracted_keywords and "additionalIndexing" in data:
            raw_indexing = data.get("additionalIndexing", "")
            # Filter out the pure structural numbers (like '24', '2846')
            tags = [t.strip() for t in raw_indexing.split(";") if not t.strip().isdigit()]
            extracted_keywords.extend(tags)

        # Deduplicate while keeping sequence order
        keywords_str = ", ".join(list(dict.fromkeys(extracted_keywords)))
        # -----------------------------------------------------------

        texts = data.get('texts', [])
        bill_metadata = {
            "title": data.get("title"),
            "keywords": keywords_str,  # Populates: "Wohneigentum, Grundstückgewinnsteuer, ..."
            "ideological_summary": "",
            "statutory_text": ""
        }

        for text in texts:
            text_type_name = text.get("type", {}).get("name")
            raw_value = text.get("value", "")

            clean_value = re.sub(r'<[^>]+>', ' ', html.unescape(raw_value))
            clean_value = ' '.join(clean_value.split())

            if text_type_name in ["Développement", "Bedeutung und Begründung", "Development"]:
                bill_metadata["ideological_summary"] = clean_value
            elif text_type_name in ["Texte déposé", "Eingereichter Text", "Submitted text"]:
                bill_metadata["statutory_text"] = clean_value

        return bill_metadata

    print(f"Error fetching data. Status code: {response.status_code}")
    return None

In [6]:
def business_number_to_affair_id(normalized_str):
    if pd.isna(normalized_str) or normalized_str in ['nan', 'NaN']:
        return np.nan

    left, right = normalized_str.split('.')
    year_short = int(left)
    sequence = int(right)

    # 1. Deduce the 4-digit century year
    # Adjust the cutoff threshold dynamically depending on the data age
    if year_short <= 26:
        year_full = 2000 + year_short
    else:
        year_full = 1900 + year_short

    # 2. Left-pad the integer sequence to create the 8-digit block
    # Equivalent to: (year_full * 10000) + sequence
    affair_id = f"{year_full}{str(sequence).zfill(4)}"
    return affair_id

In [7]:
import re
import pandas as pd
from tqdm import tqdm
from transformers import pipeline


# --------------------------------------------------
# Fast heuristic filter
# --------------------------------------------------

def has_heuristic_procedural_patterns(text):
    text = str(text).strip()

    if text == "":
        return True

    patterns = [
        r"^\[vs\]$",
        r"^angenommen\s*-\s*adopté$",
        r"^adopté\s*-\s*angenommen$",
        r"^das wort hat$",
        r"^le parole est à$",
    ]

    for p in patterns:
        if re.search(p, text, flags=re.IGNORECASE):
            return True

    if len(text.split()) < 3:
        return True

    return False

In [8]:
# --------------------------------------------------
# Zero-shot discourse classifier
# --------------------------------------------------

DISCOURSE_LABELS = [
    "Procedural parliamentary remark",
    "Legislative background or factual context",
    "Policy evidence or justification",
    "Policy argument",
    "Explicit policy recommendation or stance",
]

In [9]:
def classify_discourse_paragraphs(
    df,
    text_col="TEXT_SPAN",
    batch_size=64,
    model_name="MoritzLaurer/bge-m3-zeroshot-v2.0",
):

    classifier = pipeline(
        "zero-shot-classification",
        model=model_name,
        device=torch.device("cuda" if torch.cuda.is_available() else "cpu")
    )

    df = df.copy()

    # obvious procedural
    heuristic_mask = df[text_col].apply(has_heuristic_procedural_patterns)

    df["discourse_label"] = "Procedural parliamentary remark"
    df["confidence"] = 1.0

    label_cols = {
        label: []
        for label in DISCOURSE_LABELS
    }

    to_predict = df.loc[~heuristic_mask]

    texts = to_predict[text_col].fillna("").astype(str).tolist()

    outputs = classifier(
        texts,
        candidate_labels=DISCOURSE_LABELS,
        multi_label=False,
        batch_size=batch_size,
    )

    for row_idx, out in zip(to_predict.index, outputs):

        best_label = out["labels"][0]
        best_score = out["scores"][0]

        df.loc[row_idx, "discourse_label"] = best_label
        df.loc[row_idx, "confidence"] = best_score

        score_dict = dict(zip(out["labels"], out["scores"]))

        for label in DISCOURSE_LABELS:
            value = score_dict.get(label, 0.0)
            label_cols[label].append((row_idx, value))

    for label in DISCOURSE_LABELS:

        column = (
            label.lower()
            .replace(" ", "_")
            .replace("/", "_")
        )

        df[column] = 0.0

        for idx, score in label_cols[label]:
            df.loc[idx, column] = score

    return df

In [10]:
import pandas as pd
df = pd.read_csv("data/speeches_with_text.csv")

In [11]:
df

,Speech_ID,speaker_uid,speaker_first_name,speaker_last_name,speaker_fullname,party,party_name,gender,source_name,source_abbrev,meeting_uid,meeting_number,meeting_datetime,meeting_date,session_name,year,legislative_period_uid,Debate_ID,Bill_Number,Bill_Title_DE,Bill_Title_FR,Bill_Labels,Discussion_ID,Partition_ID,Paragraph_ID,name,role,language_of_text,TEXT_SPAN
0,81893,453.0,André,Bugnon,Bugnon André,SVP,Schweizerische Volkspartei,m,Online DB,ODB,941.0,12.0,2007-12-20T08:00:00.000000000,2007-12-20,Winter session,2007.0,48.0,06_405.5,6.405,Verdoppelung der Anzahl Durchdiener,Doublement de la proportion de militaires en s...,Bill|Parliamentary Initiative,12870.0,12870.1,1,Bugnon André,President,FR,La commission propose de ne pas donner suite à...
1,81893,453.0,André,Bugnon,Bugnon André,SVP,Schweizerische Volkspartei,m,Online DB,ODB,941.0,12.0,2007-12-20T08:00:00.000000000,2007-12-20,Winter session,2007.0,48.0,06_405.5,6.405,Verdoppelung der Anzahl Durchdiener,Doublement de la proportion de militaires en s...,Bill|Parliamentary Initiative,12870.0,12870.1,2,Bugnon André,President,FR,[VS]
2,81893,453.0,André,Bugnon,Bugnon André,SVP,Schweizerische Volkspartei,m,Online DB,ODB,941.0,12.0,2007-12-20T08:00:00.000000000,2007-12-20,Winter session,2007.0,48.0,06_405.5,6.405,Verdoppelung der Anzahl Durchdiener,Doublement de la proportion de militaires en s...,Bill|Parliamentary Initiative,12870.0,12870.1,3,Bugnon André,President,FR,Angenommen - Adopté
3,81894,390.0,Hans,Widmer,Widmer Hans,SP,Sozialdemokratische Partei der Schweiz,m,Online DB,ODB,941.0,12.0,2007-12-20T08:00:00.000000000,2007-12-20,Winter session,2007.0,48.0,06_405.5,6.405,Verdoppelung der Anzahl Durchdiener,Doublement de la proportion de militaires en s...,Bill|Parliamentary Initiative,12870.0,12870.1,1,Widmer Hans,For the committee,DE,"Ich möchte Sie nur nochmals bitten, das Result..."
4,81894,390.0,Hans,Widmer,Widmer Hans,SP,Sozialdemokratische Partei der Schweiz,m,Online DB,ODB,941.0,12.0,2007-12-20T08:00:00.000000000,2007-12-20,Winter session,2007.0,48.0,06_405.5,6.405,Verdoppelung der Anzahl Durchdiener,Doublement de la proportion de militaires en s...,Bill|Parliamentary Initiative,12870.0,12870.1,2,Widmer Hans,For the committee,DE,"In diesem Sinne bitte ich Sie nochmals, den An..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
666686,288682,3912.0,Christian,Wasserfallen,Wasserfallen Christian,FDP-Liberale,FDP.Die Liberalen,m,Online DB,ODB,4518.0,9.0,2021-09-23T08:00:00.000000000,2021-09-23,Fall session,2021.0,51.0,21_049.1,21.049,Gentechnikgesetz. Änderung,Loi sur le génie génétique. Modification,Bill|Federal Council Dispatch,54270.0,54270.1,8,Wasserfallen Christian,NaN,DE,Noch etwas zur Technologie: Es grenzt an Absur...
666687,288682,3912.0,Christian,Wasserfallen,Wasserfallen Christian,FDP-Liberale,FDP.Die Liberalen,m,Online DB,ODB,4518.0,9.0,2021-09-23T08:00:00.000000000,2021-09-23,Fall session,2021.0,51.0,21_049.1,21.049,Gentechnikgesetz. Änderung,Loi sur le génie génétique. Modification,Bill|Federal Council Dispatch,54270.0,54270.1,9,Wasserfallen Christian,NaN,DE,Die jüngst erschienene Befragung zeigt deutlic...
666688,288682,3912.0,Christian,Wasserfallen,Wasserfallen Christian,FDP-Liberale,FDP.Die Liberalen,m,Online DB,ODB,4518.0,9.0,2021-09-23T08:00:00.000000000,2021-09-23,Fall session,2021.0,51.0,21_049.1,21.049,Gentechnikgesetz. Änderung,Loi sur le génie génétique. Modification,Bill|Federal Council Dispatch,54270.0,54270.1,10,Wasserfallen Christian,NaN,DE,"Lange Forschung und Rede, kurzer Sinn: In eine..."
666689,288682,3912.0,Christian,Wasserfallen,Wasserfallen Christian,FDP-Liberale,FDP.Die Liberalen,m,Online DB,ODB,4518.0,9.0,2021-09-23T08:00:00.000000000,2021-09-23,Fall session,2021.0,51.0,21_049.1,21.049,Gentechnikgesetz. Änderung,Loi sur le génie génétique. Modification,Bill|Federal Council Dispatch,54270.0,54270.1,11,Wasserfallen Christian,NaN,DE,"Ich bitte Sie deshalb, wenigstens der Minderhe..."
666690,288683,4134.0,Martina,Munz,Munz Martina,SP,Sozialdemokratische Partei der Schweiz,f,Online DB,ODB,4518.0,9.0,2021-09-23T08:00:00.000000000,2021-09-23,Fall session,2021.0,51.0,21_049.1,21.049,Gentechnikgesetz. Änderung,Loi sur le génie génétique. Modification,Bill|Federal Council Dispatch,54270.0,54270.1,1,Munz Martina,NaN,DE,"Herr Kollege Wasserfallen, Sie haben nicht ges..."

In [12]:
# Select Motion and Parliamentary Initiative bills
df = df[df['Bill_Labels'].isin(['Bill|Motion', 'Bill|Parliamentary Initiative'])]

In [13]:
# Apply normalization helpers to the raw dataset first
df['Bill_Number'] = df['Bill_Number'].apply(normalize_swiss_bill)

# Drop rows where Bill_Number or TEXT_SPAN is missing
df = df.dropna(subset=['Bill_Number', 'TEXT_SPAN', 'language_of_text'])
df['lang'] = df['language_of_text'].str.upper().str.strip()

# Generate Affair_ID for the API calls
df['Affair_ID'] = df['Bill_Number'].apply(business_number_to_affair_id)

/tmp/ipykernel_2377/1588943188.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Bill_Number'] = df['Bill_Number'].apply(normalize_swiss_bill)

In [14]:
# How many bills?
df['Bill_Number'].nunique()

5386

In [15]:
N_TARGET_BILLS = 20
dense_multilingual_bills = df.groupby('Bill_Number').size().sort_values(ascending=False).head(N_TARGET_BILLS).index.tolist()

print("Example selected bills:", dense_multilingual_bills)

Example selected bills: ['10.443', '21.501', '19.401', '19.475', '09.528', '19.443', '04.476', '05.453', '19.400', '08.445', '21.502', '07.400', '06.441', '13.468', '17.400', '12.400', '07.492', '16.457', '04.430', '10.467']

In [16]:
# Filter our main dataframe to only contain these dense bills
df_filtered = df[df['Bill_Number'].isin(dense_multilingual_bills)].copy().reset_index(drop=True)

In [17]:
import requests

bill_metadata_cache = {}
unique_affairs = df_filtered['Affair_ID'].dropna().unique()

In [18]:
unique_affairs[0]

'20040476'

In [19]:
fetch_bill_metadata(unique_affairs[0])

{'title': "Protection de la population et de l'économie contre le tabagisme passif",
 'keywords': 'Tabakkonsum, Nikotinsucht, Gesundheitszustand, Gaststättengewerbe, Gastronomieberuf, öffentliches Gebäude, Arbeitsstätte, Schule, Spital, öffentlicher Verkehr',
 'ideological_summary': "Situation de départ et action nécessaire Chaque jour, même sans avoir jamais fumé, quelqu'un meurt en Suisse à cause du tabagisme. Au cours d'une année, ils sont des milliers à tomber malades, dont beaucoup sont gravement atteints. Tous les âges sont touchés. Les coûts pour la santé publique et pour notre économie sont considérables, les souffrances sont grandes et une forte majorité de la population suisse voit sa liberté quotidienne sensiblement réduite. L'industrie du tabac reconnaît, par ailleurs, que le tabagisme vis-à-vis des tiers, dit tabagisme passif, rend malade et tue. Elle aussi se prononce en faveur de mesures contre le tabagisme passif, qui est la pire source de pollution des espaces intérieurs. Il n'est pas possible de fixer un seuil de tolérance, car toute quantité, si minime soit-elle, est cancérigène. Même en se responsabilisant, les personnes - 75 % de la population ne consomme pas de tabac - et les institutions ne peuvent pas se prémunir contre les dommages causés par ce tabagisme passif. Les uns et les autres ont donc besoin que soient comblées les lacunes du droit en vigueur. Bases constitutionnelles La Confédération peut légiférer sur la protection de la population contre le tabagisme passif. Les avis de droit de l'Office fédéral de la justice (2003) et de Tobias Jaag, professeur de droit public et constitutionnel à l'Université de Zurich (2004) sont explicites sur le sujet. (Art. 74 Cst.; art. 110 al. 1 let. a Cst.; art. 118 al. 2 let. a et b Cst.). Solution La protection de la population et de l'économie contre les effets nocifs et limitatifs du tabagisme passif est obtenue par la modification du droit en vigueur (p. ex. loi sur le travail, loi sur les denrées alimentaires, ordonnance sur le tabac, loi fédérale sur les transports publics). Il n'est pas nécessaire d'élaborer une nouvelle loi. La présente initiative complète le rapport sur la protection contre le tabagisme passif demandé par la Commission de l'économie et des redevances (Po. CER-N 02.3379). Elle indique les moyens de réaliser les travaux législatifs urgents qui sont requis. Avantages de cette solution La protection de la population et de l'économie contre les effets nocifs et limitatifs du tabagisme passif ne constitue pas une restriction excessive de la liberté du commerce et de l'industrie ni de la liberté personnelle des consommateurs de tabac. Les mesures correspondent aux dispositions européennes que nous devons prendre en compte en vertu des accords qui ont été passés, elles correspondent également à la convention-cadre de l'OMS sur le tabac, que la Confédération a signée en 2004. Selon l'avis de droit mentionné ci-dessus, les mesures sont adaptées et proportionnées : elles visent la protection de ceux qui sont involontairement exposés à la fumée de tabac, qui en subissent des dommages contre lesquels ils sont impuissants. Elles n'imposent pas de limitations excessives aux consommateurs, mais créent la clarté et des espaces de liberté. Cette solution n'entraîne de frais ni pour les pouvoirs publics ni pour l'économie, et elle peut même être d'un bon rapport pour l'économie. Une solution d'urgence s'impose. Elle intéresse 75 % de la population et de larges milieux économiques. Elle est en mesure de réduire massivement les coûts, notamment des maladies, et elle a le potentiel de faire baisser notablement la mortalité - jusqu'à 400 décès pourraient être évités chaque année en Suisse - et de prévenir des milliers de cas de maladies.",
 'statutory_text': "Conformément à l'art. 160, al. 1, de la Constitution et l'article 107 de la loi sur le Parlement, je présente l'initiative parlementaire suivante : La population et l'économie sont protégées contre les effets nocifs et limitatifs du tabagisme passif. À cet effet, le droit en vigueur est modifié de telle façon que la protection est assurée en particulier dans les établissements de formation, les établissements hospitaliers et de soins, l'administration publique, sur le lieu de travail et dans les locaux et moyens de transport auxquels le public a libre accès ou qu'il utilise."}

In [20]:
for affair_id in tqdm(unique_affairs, desc="Fetching Bill Metadata"):
    meta = fetch_bill_metadata(affair_id)
    if meta:
        bill_metadata_cache[affair_id] = meta

Fetching Bill Metadata: 100% 20/20 [00:03<00:00,  5.23it/s]

In [21]:
bill_metadata_cache

{'20040476': {'title': "Protection de la population et de l'économie contre le tabagisme passif",
  'keywords': 'Tabakkonsum, Nikotinsucht, Gesundheitszustand, Gaststättengewerbe, Gastronomieberuf, öffentliches Gebäude, Arbeitsstätte, Schule, Spital, öffentlicher Verkehr',
  'ideological_summary': "Situation de départ et action nécessaire Chaque jour, même sans avoir jamais fumé, quelqu'un meurt en Suisse à cause du tabagisme. Au cours d'une année, ils sont des milliers à tomber malades, dont beaucoup sont gravement atteints. Tous les âges sont touchés. Les coûts pour la santé publique et pour notre économie sont considérables, les souffrances sont grandes et une forte majorité de la population suisse voit sa liberté quotidienne sensiblement réduite. L'industrie du tabac reconnaît, par ailleurs, que le tabagisme vis-à-vis des tiers, dit tabagisme passif, rend malade et tue. Elle aussi se prononce en faveur de mesures contre le tabagisme passif, qui est la pire source de pollution des espaces intérieurs. Il n'est pas possible de fixer un seuil de tolérance, car toute quantité, si minime soit-elle, est cancérigène. Même en se responsabilisant, les personnes - 75 % de la population ne consomme pas de tabac - et les institutions ne peuvent pas se prémunir contre les dommages causés par ce tabagisme passif. Les uns et les autres ont donc besoin que soient comblées les lacunes du droit en vigueur. Bases constitutionnelles La Confédération peut légiférer sur la protection de la population contre le tabagisme passif. Les avis de droit de l'Office fédéral de la justice (2003) et de Tobias Jaag, professeur de droit public et constitutionnel à l'Université de Zurich (2004) sont explicites sur le sujet. (Art. 74 Cst.; art. 110 al. 1 let. a Cst.; art. 118 al. 2 let. a et b Cst.). Solution La protection de la population et de l'économie contre les effets nocifs et limitatifs du tabagisme passif est obtenue par la modification du droit en vigueur (p. ex. loi sur le travail, loi sur les denrées alimentaires, ordonnance sur le tabac, loi fédérale sur les transports publics). Il n'est pas nécessaire d'élaborer une nouvelle loi. La présente initiative complète le rapport sur la protection contre le tabagisme passif demandé par la Commission de l'économie et des redevances (Po. CER-N 02.3379). Elle indique les moyens de réaliser les travaux législatifs urgents qui sont requis. Avantages de cette solution La protection de la population et de l'économie contre les effets nocifs et limitatifs du tabagisme passif ne constitue pas une restriction excessive de la liberté du commerce et de l'industrie ni de la liberté personnelle des consommateurs de tabac. Les mesures correspondent aux dispositions européennes que nous devons prendre en compte en vertu des accords qui ont été passés, elles correspondent également à la convention-cadre de l'OMS sur le tabac, que la Confédération a signée en 2004. Selon l'avis de droit mentionné ci-dessus, les mesures sont adaptées et proportionnées : elles visent la protection de ceux qui sont involontairement exposés à la fumée de tabac, qui en subissent des dommages contre lesquels ils sont impuissants. Elles n'imposent pas de limitations excessives aux consommateurs, mais créent la clarté et des espaces de liberté. Cette solution n'entraîne de frais ni pour les pouvoirs publics ni pour l'économie, et elle peut même être d'un bon rapport pour l'économie. Une solution d'urgence s'impose. Elle intéresse 75 % de la population et de larges milieux économiques. Elle est en mesure de réduire massivement les coûts, notamment des maladies, et elle a le potentiel de faire baisser notablement la mortalité - jusqu'à 400 décès pourraient être évités chaque année en Suisse - et de prévenir des milliers de cas de maladies.",
  'statutory_text': "Conformément à l'art. 160, al. 1, de la Constitution et l'article 107 de la loi sur le Parlement, je présente l'initiative parlementaire suivante : La population et l'économie sont protégées contre les effets nocifs et limitatifs du tabagisme passif. À cet effet, le droit en vigueur est modifié de telle façon que la protection est assurée en particulier dans les établissements de formation, les établissements hospitaliers et de soins, l'administration publique, sur le lieu de travail et dans les locaux et moyens de transport auxquels le public a libre accès ou qu'il utilise."},
 '20060441': {'title': 'Pour une protection du consommateur contre les abus du démarchage téléphonique',
  'keywords': 'Telefon, Verkauf, Konsumentenschutz, Vertrag des Privatrechts, Kündigung eines Vertrags, Obligationenrecht',
  'ideological_summary': "La plupart des habitants de notre pays ont certainement déjà eu affaire une ou plusieurs fois à des démarcheurs par téléphone, agissant pour le compte d'opérateurs de télécommunication, de vendeurs de produits de bien-être et de beauté ou d'autres biens ou services commerciaux. Les défenseurs des consommateurs reçoivent quotidiennement des plaintes de la part de personnes qui se plaignent des agissements de démarcheurs téléphoniques particulièrement tenaces voire agressifs. Fréquemment, les personnes appelées découvrent après quelque temps qu'elles ont été considérées comme ayant donné leur accord à une transaction (achat, changement d'opérateur téléphonique) alors qu'elles n'ont donné leur accord qu'à l'envoi d'une offre, voire pas donné leur accord du tout. Actuellement, les articles 40a à 40f du Code des obligations octroient au consommateur la faculté de révoquer dans un délai de sept jours un contrat conclu à l'occasion d'un démarchage à domicile, au lieu de travail, dans les transports publics, sur la voie publique ou lors d'une excursion publicitaire. Ce droit ne concerne toutefois pas les contrats conclus lors d'un démarchage téléphonique. Dans son projet de loi sur le commerce électronique de janvier 2001, portant révision du Code de obligations et de la loi fédérale contre la concurrence déloyale, le Conseil fédéral prévoyait d'étendre le droit de révocation aux contrats conclus à distance, soit notamment par Internet et par téléphone. Après avoir chargé, le 9 décembre 2002, le DFJP d'élaborer un message sur la base du résultat de la procédure de consultation, le Conseil fédéral a décidé, le 9 novembre 2005, de retirer son projet. Lors de la procédure de consultation, il est apparu que la possibilité de révoquer un contrat conclu par Internet suscitait des oppositions. Si l'on peut admettre que, dans la conclusion d'une transaction en ligne, le consommateur n'est pas soumis à la pression du vendeur et que l'octroi du droit de révocation est alors discutable, la situation présentée par le démarchage téléphonique est très différente. Elle s'apparente de manière évidente au démarchage physique à domicile ou sur la voie publique, avec un vendeur exerçant une pression sur un client potentiel. Il apparaît donc pleinement justifié d'octroyer le droit de révocation dans un tel cas. Ce droit est d'autant plus justifié qu'aucun accord écrit n'est donné dans une transaction téléphonique. Exiger que le client reçoive confirmation écrite de son accord, réel ou supposé, à une transaction téléphonique, avec droit de révocation, permettrait de restreindre fortement les abus constatés dans ce domaine.",
  'statutory_text': "Conformément à l'art. 160, al. 1, de la Constitution et à l'article 107 de la loi sur le Parlement, je dépose l'initiative parlementaire suivante : Afin de mettre un terme aux abus constatés dans le domaine du démarchage téléphonique où le consommateur se voit fréquemment considéré comme ayant donné son accord à une transaction commerciale, sans droit de révocation, il convient de modifier le Code des obligations en son article 40a (ou éventuellement 40b), afin que le démarchage téléphonique soit assimilé au démarchage à domicile et que le consommateur dispose ainsi du droit de révocation prévu aux articles 40b à 40f."},
 '20100467': {'title': "Prévention de l'endettement par l'interdiction de la publicité en faveur des petits crédits",
  'keywords': 'Werbeverbot, Konsumkredit, Verschuldung',
  'ideological_summary': 'L\'année 2010 a été promulguée "Ànnée européenne de lutte contre la pauvreté et l\'exclusion sociale". La pauvreté est souvent liée à un cercle vicieux qui s\'installe dès la jeunesse, par de petites difficultés qui s\'accumulent. Un des éléments peut être le glissement vers un endettement beaucoup trop élevé qui pénalise de manière durable toute tentative de refaire surface. Les services sociaux des cantons connaissent bien ces situations et la Commission fédérale pour l\'enfance et la jeunesse dans son rapport d\'août 2007 intitulé "Jeune et pauvre : un tabou à briser !" a demandé l\'interdiction de la publicité en faveur des petits crédits. Les cantons se heurtent à une loi fédérale qui ne leur permet pas de légiférer sur le sujet (art. 38 LCC). Le problème est pourtant bien réel et concerne en premier chef les jeunes : - un quart des jeunes entre 16 et 25 ans dépensent plus d\'argent qu\'ils ne peuvent se le permettre ; - 80 % des jeunes endettés l\'ont été pour la première fois avant l\'âge de 25 ans ; - 85 % des jeunes entre 14 et 24 ans considèrent le shopping comme une part importante de leurs loisirs ; - 33 % de la population a tendance à ne pas pouvoir contrôler son comportement en matière d\'achat. (Sources : Commission fédérale de la consommation 2005, Association des sociétés fiduciaires de recouvrement.) Je souhaite que des mesures préventives soient prises pour lutter contre cette situation dangereuse pour les personnes concernées, malsaine pour le pays (une population qui vit à crédit peut conduire à des catastrophes économiques), et inutilement lourde pour les finances publiques par le nombre de personnes qui aboutissent à l\'aide sociale suite à des endettements qui les étranglent. Lors des dernières modifications de la LCC et de la LCD, les discussions de fond n\'ont pas eu lieu au Parlement, l\'initiative parlementaire Rossini 06.417, plus exigeante, a échoué à une voix près, et deux autres motions ont été classées sans traitement après deux ans. Le problème n\'est pas résolu pour autant. En cette "Ànnée européenne de lutte contre la pauvreté et l\'exclusion sociale", c\'est le bon moment pour remettre l\'ouvrage sur le métier.',
  'statutory_text': "Conformément à l'art. 160, al. 1, de la Constitution et à l'article 107 de la loi sur le Parlement, je dépose l'initiative parlementaire suivante : Je demande une modification de la loi fédérale sur le crédit à la consommation (LCC), ou éventuellement de la loi fédérale contre la concurrence déloyale (LCD), qui interdise la publicité pour les petits crédits."},
 '20160457': {'title': 'Modifications diverses du droit parlementaire',
  'keywords': '',
  'ideological_summary': '',
  'statutory_text': 'La Commission des institutions politiques du Conseil national décide de mettre en oeuvre dans le cadre d\'un projet unique les initiatives parlementaires suivantes, qui portent sur différentes modifications du droit parlementaire et auxquelles les Commissions des institutions politiques des deux conseils ont donné suite : - Iv. pa. Streiff 14.472, "Liens d\'intérêts des parlementaires. Accroître la transparence"; - Iv. pa. 15.425 CdI-N, "Immunité. Traitement des demandes par les présidents des deux commissions"; - Iv. pa. Keller Peter 15.437, "Registre des intérêts. Distinguer les activités bénévoles des activités rémunérées"; - Iv. pa. Minder 15.444, "Commissions parlementaires. Prévoir la possibilité de rendre publics les documents secondaires". S\'il est également donné suite aux initiatives parlementaires ci-après, celles-ci seront aussi mises en oeuvre dans le cadre du projet unique : - Iv. pa. Leutenegger Oberholzer 16.409, "Procédure de désignation du Préposé fédéral à la protection des données et à la transparence"; - Iv. pa. Caroni 16.446, "Davantage de fédéralisme dans les messages du Conseil fédéral". Il convient par ailleurs d\'examiner la possibilité d\'intégrer d\'autres modifications du droit parlementaire dans le projet unique.'},
 '20130468': {'title': 'Mariage civil pour tous',
  'keywords': 'Eheschliessung, gleichgeschlechtliches Paar, sexuelle Minderheit, Gleichbehandlung',
  'ideological_summary': 'La présente initiative demande au législateur d\'ouvrir les différentes formes d\'union régies par la loi à tous les couples, quels que soient le sexe ou l\'orientation sexuelle des partenaires. Les couples de même sexe doivent pouvoir se marier, et les couples de sexe différent doivent pouvoir eux aussi conclure un partenariat enregistré, comme c\'est le cas en France. La modification de l\'art. 14, al. 2, Cst., que nous proposons, fixe ces principes. À l\'art. 14, al. 1, la notion de "mariage" est remplacée par la notion plus large d\'"union". Ce remplacement entend conférer aux formes d\'union telles que le partenariat enregistré ou le concubinat le statut de droit fondamental que la Constitution accorde au mariage. La simple cohabitation avec une ou plusieurs personnes (communauté d\'habitation par ex.) ne relèvera pas de l\'art. 14, al. 1, Cst. Cette disposition n\'obligera pas non plus le législateur à ouvrir l\'adoption aux couples homosexuels. À l\'art. 38, al. 1, première phrase, le terme "mariage" est remplacé par la notion plus large d\'"union (régie par la loi)". Les êtres humains se marient surtout pour donner une base durable à leur union, s\'assurer une sécurité financière réciproque et exprimer leur engagement face à la société. En Suisse, ces droits sont refusés à une partie de la société. Et ceux auxquels ils sont déniés n\'ont d\'autre choix que de conclure une sorte de mariage au rabais sous la forme d\'un partenariat enregistré. Cette différence de statut, fondée sur de seules différences biologiques, est contraire aux valeurs libérales de notre société et aux principes d\'un État moderne. Les États qui ont choisi de légaliser le mariage entre personnes de même sexe, dont la France, l\'Espagne, le Portugal, la Belgique, les Pays-Bas, la Norvège, la Suède, le Danemark, l\'Islande et bien d\'autres encore, l\'ont d\'ailleurs bien compris. La présente initiative n\'entend pas non plus dicter aux Églises et aux autres communautés religieuses qui pourra se marier ou non selon les rites de sa foi. Elles continueront de se déterminer librement à ce sujet.',
  'statutory_text': 'Conformément à l\'art. 160, al. 1, de la Constitution et à l\'article 107 de la loi sur le Parlement, je dépose l\'initiative parlementaire suivante : La Constitution fédérale sera modifiée comme suit : Art. 14 Droit au mariage, à l\'union (nouveau) et à la famille Al. 1 Le droit au mariage, à l\'union (nouveau) et à la famille est garanti. Al. 2 Les formes d\'union régies par la loi sont ouvertes à tous les couples quels que soient leur sexe ou leur orientation sexuelle. Art. 38 al. 1 première phrase La Confédération règle l\'acquisition et la perte de la nationalité et des droits de cité par filiation, par union (supprimer "par mariage") ou par adoption. (...)'},
 '20070400': {'title': 'Droit parlementaire. Modifications diverses',
  'keywords': 'Motion, Frist, parlamentarische Initiative, Haftung, Parlamentarier/in, parlamentarisches Verfahren, Gesetz, Fraktion, parlamentarische Kommission, Sitzverteilung in Kommissionen, fraktionslose Abgeordnete, Petition',
  'ideological_summary': '',
  'statutory_text': ''},
 '20050453': {'title': 'Interdiction des pitbulls en Suisse',
  'keywords': 'Hund, Bewilligung, Tierhaltung',
  'ideological_summary': "Suite aux événements dramatiques qui ont secoué notre pays concernant le décès d'un enfant attaqué par trois chiens de race pitbull, il est temps que la Suisse mette sur pied une base légale consistant à interdire ce genre de chiens sur son territoire, au même titre que l'ont fait certains pays comme la France (loi pitbull du 6 janvier 1999). En effet, il est aujourd'hui temps que des mesures draconiennes soient prises pour réduire les risques de décès ou de morsures graves occasionnés par des chiens destinés aux combats plutôt qu'à la compagnie. Ces races de chiens de combat doivent être interdites sur sol helvétique. Cette interdiction peut bien entendu être accompagnée d'autres mesures vis-à-vis des détenteurs de chiens.",
  'statutory_text': "Conformément à l'art. 160, al. 1, de la Constitution et l'article 107 de la loi sur le Parlement, je dépose l'initiative parlementaire suivante : Par la présente initiative parlementaire, je demande que la législation fédérale concernée soit modifiée de telle manière qu'il soit interdit en Suisse de posséder un chien de type pitbull et que le Conseil fédéral soit habilité à dresser une liste de races de chiens dont la présence sur sol suisse sera interdite."},
 '20120400': {'title': 'Libérer les investissements dans le renouvelable sans pénaliser les gros consommateurs',
  'keywords': 'Einspeisevergütung, erneuerbare Energie, sanfte Energie, Lenkungsabgabe, Energierecht',
  'ideological_summary': '',
  'statutory_text': "La Commission de l'environnement, de l'aménagement du territoire et de l'énergie du Conseil national décide d'élaborer une modification de la loi sur l'énergie visant à : 1. augmenter le prélèvement maximum de la RPC (art. 15b) de manière à permettre la réduction du nombre des projets en file d'attente ; 2. prévoir un dispositif d'allègement des entreprises grosses consommatrices d'électricité."},
 '20100443': {'title': 'Contre-projet indirect à l\'initiative populaire "contre les rémunérations abusives"',
  'keywords': 'Aktiengesellschaft, Lohn, Führungskraft, Verwaltungsrat, Gehaltsprämie, Gegenvorschlag, Volksinitiative, Abgangsentschädigung, zusätzliche Vergütung, höhere Führungskraft, Arbeitsentgelt, Aktienrecht, Obligationenrecht',
  'ideological_summary': '',

In [22]:
bill_metadata_df = pd.json_normalize(df_filtered['Affair_ID'].map(bill_metadata_cache))

In [23]:
df_complete = pd.concat([df_filtered.reset_index(drop=True), bill_metadata_df.reset_index(drop=True)], axis=1)

In [24]:
df_complete

,Speech_ID,speaker_uid,speaker_first_name,speaker_last_name,speaker_fullname,party,party_name,gender,source_name,source_abbrev,meeting_uid,meeting_number,meeting_datetime,meeting_date,session_name,year,legislative_period_uid,Debate_ID,Bill_Number,Bill_Title_DE,Bill_Title_FR,Bill_Labels,Discussion_ID,Partition_ID,Paragraph_ID,name,role,language_of_text,TEXT_SPAN,lang,Affair_ID,title,keywords,ideological_summary,statutory_text
0,83161,1149.0,Urs,Schwaller,Schwaller Urs,CVP,Christlichdemokratische Volkspartei der Schweiz,m,Online DB,ODB,962.0,2.0,2008-03-04T08:05:00.000000000,2008-03-04,Spring session,2008.0,48.0,04_476.4,04.476,Schutz der Bevölkerung und der Wirtschaft vor ...,Protection de la population et de l'économie c...,Bill|Parliamentary Initiative,13158.0,13158.1,1,Schwaller Urs,For the committee,DE,Ein einziger Satz: Wir waren hier der Auffassu...,DE,20040476,Protection de la population et de l'économie c...,"Tabakkonsum, Nikotinsucht, Gesundheitszustand,...",Situation de départ et action nécessaire Chaqu...,"Conformément à l'art. 160, al. 1, de la Consti..."
1,83162,425.0,Rolf,Schweiger,Schweiger Rolf,FDP-Liberale,FDP.Die Liberalen,m,Online DB,ODB,962.0,2.0,2008-03-04T08:05:00.000000000,2008-03-04,Spring session,2008.0,48.0,04_476.4,04.476,Schutz der Bevölkerung und der Wirtschaft vor ...,Protection de la population et de l'économie c...,Bill|Parliamentary Initiative,13158.0,13158.1,1,Schweiger Rolf,NaN,DE,Ich begründe meinen Antrag ganz kurz: Gesetzli...,DE,20040476,Protection de la population et de l'économie c...,"Tabakkonsum, Nikotinsucht, Gesundheitszustand,...",Situation de départ et action nécessaire Chaqu...,"Conformément à l'art. 160, al. 1, de la Consti..."
2,83162,425.0,Rolf,Schweiger,Schweiger Rolf,FDP-Liberale,FDP.Die Liberalen,m,Online DB,ODB,962.0,2.0,2008-03-04T08:05:00.000000000,2008-03-04,Spring session,2008.0,48.0,04_476.4,04.476,Schutz der Bevölkerung und der Wirtschaft vor ...,Protection de la population et de l'économie c...,Bill|Parliamentary Initiative,13158.0,13158.1,2,Schweiger Rolf,NaN,DE,Nun ist die Sache insofern eine Blackbox-Angel...,DE,20040476,Protection de la population et de l'économie c...,"Tabakkonsum, Nikotinsucht, Gesundheitszustand,...",Situation de départ et action nécessaire Chaqu...,"Conformément à l'art. 160, al. 1, de la Consti..."
3,83162,425.0,Rolf,Schweiger,Schweiger Rolf,FDP-Liberale,FDP.Die Liberalen,m,Online DB,ODB,962.0,2.0,2008-03-04T08:05:00.000000000,2008-03-04,Spring session,2008.0,48.0,04_476.4,04.476,Schutz der Bevölkerung und der Wirtschaft vor ...,Protection de la population et de l'économie c...,Bill|Parliamentary Initiative,13158.0,13158.1,3,Schweiger Rolf,NaN,DE,[PAGE 39],DE,20040476,Protection de la population et de l'économie c...,"Tabakkonsum, Nikotinsucht, Gesundheitszustand,...",Situation de départ et action nécessaire Chaqu...,"Conformément à l'art. 160, al. 1, de la Consti..."
4,83163,276.0,Christoffel,Brändli,Brändli Christoffel,SVP,Schweizerische Volkspartei,m,Online DB,ODB,962.0,2.0,2008-03-04T08:05:00.000000000,2008-03-04,Spring session,2008.0,48.0,04_476.4,04.476,Schutz der Bevölkerung und der Wirtschaft vor ...,Protection de la population et de l'économie c...,Bill|Parliamentary Initiative,13158.0,13158.1,1,Brändli Christoffel,President,DE,Die Kommission beantragt aufgrund der Abstimmu...,DE,20040476,Protection de la population et de l'économie c...,"Tabakkonsum, Nikotinsucht, Gesundheitszustand,...",Situation de départ et action nécessaire Chaqu...,"Conformément à l'art. 160, al. 1, de la Consti..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14934,288162,4152.0,Hans,Wicki,Wicki Hans,FDP-Liberale,FDP.Die Liberalen,m,Online DB,ODB,4514.0,6.0,2021-09-21T08:05:00.000000000,2021-09-21,Fall session,2021.0,51.0,17_400.3,17.400,Systemwechsel bei der Wohneigentumsbesteuerung,Imposition du logement. Changement de système,Bill|Parliamentary Initiative,54173.0,54173.2,1,Wicki Hans,NaN,DE,Meine Vorredner haben jetzt eindrücklich erläu...,DE,20170400,Imposition du logement. Changement de système,,,"Conformément à l'art. 160, al. 1, de la Consti..."
14935,288162,4152.0,Hans,Wicki,Wicki Hans,FDP-Liberale,FDP.Die Liberalen,m,Online DB,ODB,4514.0,6.0,2021-09-21T08:05:00.000000000,2021-09-21,Fall session,2021.0,51.0,17_400.3,17.400,Systemwechsel bei der Wohneigentumsbesteuerung,Imposition du logement. Changement de système,Bill|Parliamentary Initiative,54173.0,54173.2,2,Wicki Hans,NaN,DE,Noch eine kurze Replik zu Kollege Zanetti und ...,DE,20170400,Imposition du logement. Changement de système,,,"Conformément à l'art. 160, al. 1, de la Consti..."
14936,288162,4152.0,Hans,Wicki,Wicki Hans,FDP-Liberale,FDP.Die Liberalen,m,Online DB,ODB,4514.0,6.0,2021-09-21T08:05:00.000000000,2021-09-21,Fall session,2021.0,51.0,17_400.3,17.400,Systemwechsel bei der Wohneigentumsbesteuerung,Imposition du logement. Changement de système,Bill|Parliamentary Initiative,54173.0,54173.2,3,Wicki Hans,NaN,DE,"Abgesehen davon, dass der Antrag der Mehrheit ...",DE,20170400,Imposition du logement. Changement de système,,,"Conformément à l'art. 160, al. 1, de la Consti..."
14937,288162,4152.0,Hans,Wicki,Wicki Hans,FDP-Liberale,FDP.Die Liberalen,m,Online DB,ODB,4514.0,6.0,2021-09-21T08:05:00.000000000,2021-09-21,Fall session,2021.0,51.0,17_400.3,17.400,Systemwechsel bei der Wohneigentumsbesteuerung,Imposition du logement. Changement de système,Bill|Parliamentary Initiative,54173.0,54173.2,4,Wicki Hans,NaN,DE,Deshalb muss klar festgehalten werden: Verschu...,DE,20170400,Imposition du logement. Changement de système,,,"Conformément à l'art. 160, al. 1, de la Consti..."
14938,288162,4152.0,Hans,Wicki,Wicki Hans,FDP-Liberale,FDP.Die Liberalen,m,Online DB,ODB,4514.0,6.0,2021-09-21T08:05:00.000000000,2021-09-21,Fall session,2021.0,51.0,17_400.3,17.400,Systemwechsel bei der Wohneigentumsbesteuerung,Imposition du logement. Changement de système,Bill|Parliamentary Initiative,54173.0,54173.2,5,Wicki Hans,NaN,DE,"Ich empfehle Ihnen deshalb, unserer Minderheit...",DE,20170400,Imposition du logement. Changement de système,,,"Conformément à l'art. 160, al. 1, de la Consti..."

In [37]:
aggregation = {
    k: "first" for k in df_complete.columns if k != "Speech_ID"
}
aggregation["TEXT_SPAN"] = lambda x: " ".join(x.astype(str))

df_speech_level = (
    df_complete
    .groupby("Speech_ID")
    .agg(aggregation)
    .reset_index()
)

In [41]:
df_speech_level

,Speech_ID,speaker_uid,speaker_first_name,speaker_last_name,speaker_fullname,party,party_name,gender,source_name,source_abbrev,meeting_uid,meeting_number,meeting_datetime,meeting_date,session_name,year,legislative_period_uid,Debate_ID,Bill_Number,Bill_Title_DE,Bill_Title_FR,Bill_Labels,Discussion_ID,Partition_ID,Paragraph_ID,name,role,language_of_text,TEXT_SPAN,lang,Affair_ID,title,keywords,ideological_summary,statutory_text
0,83161,1149.0,Urs,Schwaller,Schwaller Urs,CVP,Christlichdemokratische Volkspartei der Schweiz,m,Online DB,ODB,962.0,2.0,2008-03-04T08:05:00.000000000,2008-03-04,Spring session,2008.0,48.0,04_476.4,04.476,Schutz der Bevölkerung und der Wirtschaft vor ...,Protection de la population et de l'économie c...,Bill|Parliamentary Initiative,13158.0,13158.1,1,Schwaller Urs,For the committee,DE,Ein einziger Satz: Wir waren hier der Auffassu...,DE,20040476,Protection de la population et de l'économie c...,"Tabakkonsum, Nikotinsucht, Gesundheitszustand,...",Situation de départ et action nécessaire Chaqu...,"Conformément à l'art. 160, al. 1, de la Consti..."
1,83162,425.0,Rolf,Schweiger,Schweiger Rolf,FDP-Liberale,FDP.Die Liberalen,m,Online DB,ODB,962.0,2.0,2008-03-04T08:05:00.000000000,2008-03-04,Spring session,2008.0,48.0,04_476.4,04.476,Schutz der Bevölkerung und der Wirtschaft vor ...,Protection de la population et de l'économie c...,Bill|Parliamentary Initiative,13158.0,13158.1,1,Schweiger Rolf,None,DE,Ich begründe meinen Antrag ganz kurz: Gesetzli...,DE,20040476,Protection de la population et de l'économie c...,"Tabakkonsum, Nikotinsucht, Gesundheitszustand,...",Situation de départ et action nécessaire Chaqu...,"Conformément à l'art. 160, al. 1, de la Consti..."
2,83163,276.0,Christoffel,Brändli,Brändli Christoffel,SVP,Schweizerische Volkspartei,m,Online DB,ODB,962.0,2.0,2008-03-04T08:05:00.000000000,2008-03-04,Spring session,2008.0,48.0,04_476.4,04.476,Schutz der Bevölkerung und der Wirtschaft vor ...,Protection de la population et de l'économie c...,Bill|Parliamentary Initiative,13158.0,13158.1,1,Brändli Christoffel,President,DE,Die Kommission beantragt aufgrund der Abstimmu...,DE,20040476,Protection de la population et de l'économie c...,"Tabakkonsum, Nikotinsucht, Gesundheitszustand,...",Situation de départ et action nécessaire Chaqu...,"Conformément à l'art. 160, al. 1, de la Consti..."
3,83164,1149.0,Urs,Schwaller,Schwaller Urs,CVP,Christlichdemokratische Volkspartei der Schweiz,m,Online DB,ODB,962.0,2.0,2008-03-04T08:05:00.000000000,2008-03-04,Spring session,2008.0,48.0,04_476.4,04.476,Schutz der Bevölkerung und der Wirtschaft vor ...,Protection de la population et de l'économie c...,Bill|Parliamentary Initiative,13158.0,13158.1,1,Schwaller Urs,For the committee,DE,Ich beantrage Ihnen hier die Streichung von Ab...,DE,20040476,Protection de la population et de l'économie c...,"Tabakkonsum, Nikotinsucht, Gesundheitszustand,...",Situation de départ et action nécessaire Chaqu...,"Conformément à l'art. 160, al. 1, de la Consti..."
4,83166,50.0,Pascal,Couchepin,Couchepin Pascal,FDP-Liberale,FDP.Die Liberalen,m,Online DB,ODB,962.0,2.0,2008-03-04T08:05:00.000000000,2008-03-04,Spring session,2008.0,48.0,04_476.4,04.476,Schutz der Bevölkerung und der Wirtschaft vor ...,Protection de la population et de l'économie c...,Bill|Parliamentary Initiative,13158.0,13158.1,1,Couchepin Pascal,President of the federal council,FR,"Si vous biffez cette disposition, vous risquez...",FR,20040476,Protection de la population et de l'économie c...,"Tabakkonsum, Nikotinsucht, Gesundheitszustand,...",Situation de départ et action nécessaire Chaqu...,"Conformément à l'art. 160, al. 1, de la Consti..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3136,324986,3999.0,Katharina,Prelicz-Huber,Prelicz-Huber Katharina,Grüne,Grüne Partei,f,Online DB,ODB,4803.0,4.0,2023-09-13T15:00:00.000000000,2023-09-13,Fall session,2023.0,51.0,09_528.5,09.528,Finanzierung der Gesundheitsleistungen aus ein...,Financement moniste des prestations de soins,Bill|Parliamentary Initiative,61604.0,61604.1,1,Prelicz-Huber Katharina,None,DE,Bei Artikel 18 sind wir Grünen bei der Mehrhei...,DE,20090528,Financement moniste des prestations de soins,"Krankenversicherung, Finanzierungsart, öffentl...",Les bases de la 3e révision de la LAMal ont ét...,"Conformément à l'art. 160, al. 1, de la Consti..."
3137,324991,4282.0,Thomas,Rechsteiner,Rechsteiner Thomas,CVP,Christlichdemokratische Volkspartei der Schweiz,m,Online DB,ODB,4803.0,4.0,2023-09-13T15:00:00.000000000,2023-09-13,Fall session,2023.0,51.0,09_528.5,09.528,Finanzierung der Gesundheitsleistungen aus ein...,Financement moniste des prestations de soins,Bill|Parliamentary Initiative,61604.0,61604.1,1,Rechsteiner Thomas,None,DE,Die Mitte-Fraktion setzt sich für Efas ein. Se...,DE,20090528,Financement moniste des prestations de soins,"Krankenversicherung, Finanzierungsart, öffentl...",Les bases de la 3e révision de la LAMal ont ét...,"Conformément à l'art. 160, al. 1, de la Consti..."
3138,324992,4274.0,Jörg,Mäder,Mäder Jörg,GLP,Grünliberale Partei,m,Online DB,ODB,4803.0,4.0,2023-09-13T15:00:00.000000000,2023-09-13,Fall session,2023.0,51.0,09_528.5,09.528,Finanzierung der Gesundheitsleistungen aus ein...,Financement moniste des prestations de soins,Bill|Parliamentary Initiative,61604.0,61604.1,1,Mäder Jörg,None,DE,Ich nehme zuerst zu meinen Minderheitsanträgen...,DE,20090528,Financement moniste des prestations de soins,"Krankenversicherung, Finanzierungsart, öffentl...",Les bases de la 3e révision de la LAMal ont ét...,"Conformément à l'art. 160, al. 1, de la Consti..."
3139,324996,4121.0,Barbara,Gysi,Gysi Barbara,SP,Sozialdemokratische Partei der Schweiz,f,Online DB,ODB,4803.0,4.0,2023-09-13T15:00:00.000000000,2023-09-13,Fall session,2023.0,51.0,09_528.5,09.528,Finanzierung der Gesundheitsleistungen aus ein...,Financement moniste des prestations de soins,Bill|Parliamentary Initiative,61604.0,61604.1,1,Gysi Barbara,None,DE,Ich spreche für die SP-Fraktion zu Block 2. Ic...,DE,20090528,Financement moniste des prestations de soins,"Krankenversicherung, Finanzierungsart, öffentl...",Les bases de la 3e révision de la LAMal ont ét...,"Conformément à l'art. 160, al. 1, de la Consti..."
3140,324998,4094.0,Lorenz,Hess,Hess Lorenz,BDP,Bürgerlich-Demokratische Partei Schweiz,m,Online DB,ODB,4803.0,4.0,2023-09-13T15:00:00.000000000,2023-09-13,Fall session,2023.0,51.0,09_528.5,09.528,Finanzierung der Gesundheitsleistungen aus ein...,Financement moniste des prestations de soins,Bill|Parliamentary Initiative,61604.0,61604.1,1,Hess Lorenz,For the committee,DE,In Block 2 geht es bei den meisten Fragen daru...,DE,20090528,Financement moniste des prestations de soins,"Krankenversicherung, Finanzierungsart, öffentl...",Les bases de la 3e révision de la LAMal ont ét...,"Conformément à l'art. 160, al. 1, de la Consti..."

In [42]:
df_speech_level.to_csv("filtered_speech_level_data.csv", index=False)